### Get all contacts
GET http://localhost:8080/contacts

### Get single contact
GET http://localhost:8080/contacts/6965b56e59774cd21681158b

### Create new contact
POST http://localhost:8080/contacts
Content-Type: application/json

{
  "firstName": "Sarah ",
  "lastName": "Johnson",
  "email": "sarahjohnson505@gmail.com",
  "favoriteColor": "Sky Blue",
  "birthday": "2000-10-22"
}

### Update contact (YOU MUST ADD AN ID HERE!)
PUT http://localhost:8080/contacts/
Content-Type: application/json

{
  "firstName": "Sarah ",
  "lastName": "Johnson",
  "email": "sarahjohnson505@gmail.com",
  "favoriteColor": "Navy Blue",
  "birthday": "2006-8-15"
}

### Delete contact
DELETE http://localhost:8080/contacts/696b3c6cb98a0beedb57789e