### Get all contacts
GET http://localhost:8080/contacts
GET  https://cse341-l0tm.onrender.com/contacts

### Get single contact (replace ID after testing)
GET http://localhost:8080/contacts/6965b56e59774cd21681158b